### ISSUE TITLE
Unsupported PostgreSQL type: pg_snapshot

### ISSUE THREAD

**Issue by wub** [BemiHQ/BemiDB#14]
Hi! I don't necessarily want to sync these (type `pg_snapshot`), but their presence causes sync to fail.
https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-SNAPSHOT

```go
panic: Unsupported PostgreSQL type: pg_snapshot

goroutine 1 [running]:
main.(*PgSchemaColumn).parquetPrimitiveTypes(0x14000055578)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/pg_schema_column.go:337 +0x764
main.(*PgSchemaColumn).toParquetSchemaField(0x14000055578)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/pg_schema_column.go:163 +0x3c
main.PgSchemaColumn.ToParquetSchemaFieldMap({{0x140029953f0, 0x8}, {0x14002995400, 0xb}, {0x14002995410, 0xb}, {0x140029953f8, 0x2}, {0x102a40f6d, 0x1}, ...})
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/pg_schema_column.go:59 +0x28
main.(*StorageBase).WriteParquetFile(0x140006b80c8, {0x103347b98, 0x14001e29158}, {0x140000e1b88, 0x3, 0x140003ce280?}, 0x14001e29140)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/storage_base.go:32 +0x1a4
main.(*StorageLocal).CreateParquet(0x14000680e80, {0x140003ce140, 0x46}, {0x140000e1b88, 0x3, 0x4}, 0x14001e29140)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/storage_local.go:118 +0x210
main.(*IcebergWriter).Write(0x140006e6018, {{0x14000010cb0?, 0x14000010cb0?}, {0x140029c16e0?, 0x140029c16e0?}}, {0x140000e1b88, 0x3, 0x4}, 0x14001e29140)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/iceberg_writer.go:338 +0xc8
main.(*Syncer).syncFromPgTable(0x140006e6048, 0x14000394480, {{0x14000010cb0?, 0xb?}, {0x140029c16e0?, 0x0?}})
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/syncer.go:108 +0x33c
main.(*Syncer).SyncFromPostgres(0x140006e6048)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/syncer.go:46 +0x1a0
main.syncFromPg(0x1039f0520)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/main.go:74 +0x24
main.main()
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/main.go:38 +0xbc
```

**Comment by exAspArk** [comment]
Hi @wub — thank you for reporting this issue! We've added an explicit type conversion for `pg_snapshot` in the latest v0.12.0 version.
