### ISSUE TITLE
panic: Error receiving startup message: invalid length of startup packet: 1195725852

### ISSUE THREAD

**Issue by salilsaifuddin** [BemiHQ/BemiDB#18]
I encountered a panic error while starting up my application. The error message is as follows:

test@test5:~/BemiDB$ make up
devbox run --env-file .env "cd src && go run ."
2024/11/22 08:53:11 [INFO] BemiDB: Listening on 127.0.0.1:54321
2024/11/22 08:53:11 [DEBUG] DuckDB: No init file found at ./init.sql
2024/11/22 08:53:11 [DEBUG] Querying DuckDB: INSTALL iceberg
2024/11/22 08:53:11 [DEBUG] Querying DuckDB: LOAD iceberg
2024/11/22 08:53:11 [DEBUG] Querying DuckDB: CREATE SCHEMA public
2024/11/22 08:53:11 [DEBUG] Querying DuckDB: USE public
2024/11/22 08:53:11 [INFO] DuckDB: Connected
2024/11/22 08:53:23 [INFO] BemiDB: Accepted connection from 127.0.0.1:46928
panic: Error receiving startup message: invalid length of startup packet: 1195725852

goroutine 50 [running]:
main.PanicIfError({0x2bc12a0?, 0xc000127b70?}, {0xc000094ef0?, 0x0?, 0x0?})
        /home/test/BemiDB/src/utils.go:16 +0x8e
main.(*Postgres).handleStartup(0xc000138240)
        /home/test/BemiDB/src/postgres.go:157 +0x70
main.(*Postgres).Run(0xc000138240, 0xc000012018)
        /home/test/BemiDB/src/postgres.go:43 +0x25
main.start.func1()
        /home/test/BemiDB/src/main.go:65 +0x45
created by main.start in goroutine 1
        /home/test/BemiDB/src/main.go:64 +0x1ae
exit status 2
Error: error running script "cd src && go run ." in Devbox: exit status 1

**Comment by salilsaifuddin** [comment]
This issue occurred when trying to view in the browser at 127.0.0.1:54321
