### ISSUE TITLE
Server crashes when executing SELECT test WHERE test::text;

### ISSUE THREAD

**Issue by Gudwlin** [BemiHQ/BemiDB#32]
**Describe the bug**
Server crashes when executing the following psql command

**What data setup do we need to do?**
BemiDB(main) with PostgreSQL (REL_17_STABLE).

**What is the necessary configuration info needed?**
My PostgreSQL configuration:
```
./configure
```
**What is the command that caused the error?**
```
psql postgres://localhost:54321/bemidb -c "SELECT test
  WHERE test::text;"
```
backtrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1012a46]

goroutine 14 [running]:
main.(*SelectRemapper).remapTypecast(0xc00033bab0?, 0xba57b7?)
	/app/select_remapper.go:375 +0x146
main.(*SelectRemapper).remapTypeCastsInNode(0xc0006754a0?, 0xc000042180?)
	/app/select_remapper.go:257 +0x8f
main.(*SelectRemapper).remapTypeCastsInSelect(0xc0005a6b40, 0xc0006bc280)
	/app/select_remapper.go:218 +0x2d
main.(*SelectRemapper).remapSelectStatement(0xc0005a6b40, 0xc00033bc78?, 0x0)
	/app/select_remapper.go:60 +0x2f
main.(*QueryHandler).remapStatement(0xc000395520?, 0xc0005a71c0)
	/app/query_handler.go:396 +0x68
main.(*QueryHandler).remapQuery(0xc0003b6fc0, {0xc000395520, 0x1e})
	/app/query_handler.go:379 +0x166
main.(*QueryHandler).HandleQuery(0xc0003b6fc0, {0xc000395520, 0x1e})
	/app/query_handler.go:174 +0x65
main.(*Postgres).handleSimpleQuery(0xc00065dab8, 0xc0003b6fc0, 0xc000594ce0)
	/app/postgres.go:95 +0xb6
main.(*Postgres).Run(0xc00065dab8, 0xc0003b6fc0)
	/app/postgres.go:73 +0xd7
main.start.func1()
	/app/main.go:63 +0x45
created by main.start in goroutine 1
	/app/main.go:62 +0x1c5
```
**Expected behavior**
Expected ERROR to be shown or sql query to be successfully executed

Best regards,
Artyom Zarubin
Postgres Professional: https://postgrespro.com/

**Comment by exAspArk** [comment]
Hi @Gudwlin — thank you for submitting this issue! This has been resolved now.

Sending this query will return an error:

```
Query 1 ERROR at Line 1: : ERROR:  Binder Error: Referenced column "test" not found in FROM clause!
LINE 1: SELECT test WHERE test::text
                          ^
```
